# Generated by Django 5.0.6 on 2025-08-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paymentMethod',
            fields=[
                ('payId', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('payerName', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('cause', models.CharField(max_length=100)),
                ('invoices_url', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
